{
 "title": "Airflow Dashboard",
 "tags": [
  "airflow",
  "monitoring"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "state",
    "label": "State",
    "query": {
     "query": "label_values(airflow_dag_run_count, state)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "DAG Run States",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(airflow_dag_run_count{state=~\"$state\"}) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "DAG Runs Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(airflow_dag_run_count) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Task Instances Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "expr": "sum(airflow_task_instance_count) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  }
 ]
}