global:
  scrape_interval: 30s
  evaluation_interval: 30s
  scrape_timeout: 10s

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Airflow metrics
  - job_name: 'airflow'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['airflow-webserver:8080']
    scheme: http

  # Spark Master metrics
  - job_name: 'spark-master'
    metrics_path: '/metrics/master/prometheus'
    static_configs:
      - targets: ['spark-master:8080']
    scheme: http

  # Spark Worker metrics
  - job_name: 'spark-worker'
    metrics_path: '/metrics/worker/prometheus'
    static_configs:
      - targets: ['spark-worker:8081']
    scheme: http

  # Node exporter for system metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  # cAdvisor for container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
