global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'airflow'
    static_configs:
      - targets: ['airflow-webserver:8080']
  - job_name: 'spark'
    static_configs:
      - targets: ['spark-master:4040']
