global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'airflow'
    metrics_path: '/admin/metrics/'
    static_configs:
      - targets: ['airflow-webserver:8080']
    scheme: http
    tls_config:
      insecure_skip_verify: true

  - job_name: 'spark'
    metrics_path: '/metrics/executors/prometheus/'
    static_configs:
      - targets: ['spark-master:4040']
    scheme: http
    tls_config:
      insecure_skip_verify: true

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
