name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.23.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Build Docker images
        run: docker-compose build

      - name: Lint Python
        run: |
          pip install flake8
          flake8 spark/transform.py || true

      - name: Lint Java
        run: |
          sudo apt-get update && sudo apt-get install -y maven
          cd java-client && mvn checkstyle:check || true

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3

      - name: Copy files to Hostinger VPC
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.HOSTINGER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "."
          target: "~/datafusion-ingest-api-delta"

      - name: Deploy on Hostinger VPC
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.HOSTINGER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Atualiza o sistema
            sudo apt-get update
            sudo apt-get upgrade -y
            
            # Instala dependências
            sudo apt-get install -y apt-transport-https ca-certificates curl gnupg lsb-release
            
            # Adiciona a chave do Docker
            curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
            
            # Adiciona o repositório do Docker
            echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
            
            # Instala Docker e Docker Compose
            sudo apt-get update
            sudo apt-get install -y docker-ce docker-ce-cli containerd.io
            sudo curl -L "https://github.com/docker/compose/releases/download/v2.23.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
            
            # Adiciona o usuário ao grupo docker
            sudo usermod -aG docker $USER
            
            # Navega para o diretório do projeto e sobe os containers
            cd ~/datafusion-ingest-api-delta
            docker-compose down || true
            docker-compose pull || true
            docker-compose build --no-cache
            docker-compose up -d --remove-orphans
