name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Install Docker Compose and Maven
        run: |
          # Instala Docker Compose
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.23.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version
          
          # Instala Maven
          sudo apt-get update
          sudo apt-get install -y maven
          mvn -v
          
          # Verifica a versão do Java
          java -version

      - name: Build Java application
        run: |
          cd java-client
          mvn clean package -DskipTests
          mkdir -p ../docker-java-target
          cp target/coin-gecko-ingest-1.0-SNAPSHOT.jar ../docker-java-target/coin-gecko-ingest.jar

      - name: Build Docker images
        run: docker-compose build

      - name: Lint Python
        run: |
          pip install flake8
          flake8 spark/transform.py || true

      - name: Lint Java
        run: |
          sudo apt-get update && sudo apt-get install -y maven
          cd java-client && mvn checkstyle:check || true

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3

      - name: Copy files to Hostinger VPC
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.HOSTINGER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "."
          target: "~/datafusion-ingest-api-delta"
          strip_components: 1
          rm: true

      - name: Execute remote commands
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.HOSTINGER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Atualiza o sistema
            sudo apt-get update
            sudo apt-get upgrade -y
            
            # Instala dependências
            sudo apt-get install -y apt-transport-https ca-certificates curl gnupg lsb-release
            
            # Adiciona a chave do Docker
            curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
            
            # Adiciona o repositório do Docker
            echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
            
            # Instala Docker e Docker Compose
            sudo apt-get update
            sudo apt-get install -y docker-ce docker-ce-cli containerd.io
            sudo curl -L "https://github.com/docker/compose/releases/download/v2.23.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
            
            # Adiciona o usuário ao grupo docker
            sudo usermod -aG docker $USER
            
            # Cria os diretórios necessários e ajusta permissões
            mkdir -p ~/datafusion-ingest-api-delta/airflow/logs
            chmod -R 777 ~/datafusion-ingest-api-delta/airflow/logs
            
            # Navega para o diretório do projeto
            cd ~/datafusion-ingest-api-delta
            
            # Remove containers antigos
            docker-compose down -v || true
            
            # Cria rede se não existir
            docker network create datafusion-network || true
            
            # Inicia os containers
            docker-compose up -d --build
            
            # Ajusta permissões após os containers iniciarem
            sleep 10  # Aguarda os containers iniciarem
            docker exec airflow-webserver chmod -R 777 /opt/airflow/logs || true
            
            # Verifica se os containers estão rodando
            docker ps || true
